# Generated by Django 4.2.2 on 2023-07-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
